<?xml version="1.0" encoding="utf-8"?><Database Name="Humane Society" Class="HumaneSocietyDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-QGEQ024T;Initial Catalog=&quot;Humane Society&quot;;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="HumaneSociety.Properties.Settings" SettingsPropertyName="Humane_SocietyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Addresses" Member="Addresses">
    <Type Name="Address">
      <Column Name="AddressId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AddressLine1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AddressLine2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Zipcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="USStateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Address_Client" Member="Clients" ThisKey="AddressId" OtherKey="AddressId" Type="Client" />
      <Association Name="USState_Address" Member="USState" ThisKey="USStateId" OtherKey="USStateId" Type="USState" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Adoptions" Member="Adoptions">
    <Type Name="Adoption">
      <Column Name="AdoptionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClientId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnimalId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApprovalStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AdoptionFee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaymentCollected" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Animal_Adoption" Member="Animal" ThisKey="AnimalId" OtherKey="AnimalId" Type="Animal" IsForeignKey="true" />
      <Association Name="Client_Adoption" Member="Client" ThisKey="ClientId" OtherKey="ClientId" Type="Client" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Animals" Member="Animals">
    <Type Name="Animal">
      <Column Name="AnimalId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SpeciesId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Weight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DietPlanId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Demeanor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KidFriendly" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PetFriendly" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AdoptionStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Animal_Adoption" Member="Adoptions" ThisKey="AnimalId" OtherKey="AnimalId" Type="Adoption" />
      <Association Name="Animal_AnimalShot" Member="AnimalShots" ThisKey="AnimalId" OtherKey="AnimalId" Type="AnimalShot" />
      <Association Name="Animal_Room" Member="Rooms" ThisKey="AnimalId" OtherKey="AnimalId" Type="Room" />
      <Association Name="DietPlan_Animal" Member="DietPlan" ThisKey="DietPlanId" OtherKey="DietPlanId" Type="DietPlan" IsForeignKey="true" />
      <Association Name="Employee_Animal" Member="Employee" ThisKey="EmployeeId" OtherKey="EmployeeId" Type="Employee" IsForeignKey="true" />
      <Association Name="Specy_Animal" Member="Specy" ThisKey="SpeciesId" OtherKey="SpeciesId" Type="Specy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AnimalShots" Member="AnimalShots">
    <Type Name="AnimalShot">
      <Column Name="AnimalId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ShotId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DateReceived" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Animal_AnimalShot" Member="Animal" ThisKey="AnimalId" OtherKey="AnimalId" Type="Animal" IsForeignKey="true" />
      <Association Name="Shot_AnimalShot" Member="Shot" ThisKey="ShotId" OtherKey="ShotId" Type="Shot" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Clients" Member="Clients">
    <Type Name="Client">
      <Column Name="ClientId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AddressId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Income" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumberOfKids" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HomeSquareFootage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Client_Adoption" Member="Adoptions" ThisKey="ClientId" OtherKey="ClientId" Type="Adoption" />
      <Association Name="Address_Client" Member="Address" ThisKey="AddressId" OtherKey="AddressId" Type="Address" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DietPlans" Member="DietPlans">
    <Type Name="DietPlan">
      <Column Name="DietPlanId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FoodType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FoodAmountInCups" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DietPlan_Animal" Member="Animals" ThisKey="DietPlanId" OtherKey="DietPlanId" Type="Animal" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmployeeNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Employee_Animal" Member="Animals" ThisKey="EmployeeId" OtherKey="EmployeeId" Type="Animal" />
    </Type>
  </Table>
  <Table Name="dbo.Rooms" Member="Rooms">
    <Type Name="Room">
      <Column Name="RoomId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoomNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnimalId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Animal_Room" Member="Animal" ThisKey="AnimalId" OtherKey="AnimalId" Type="Animal" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Shots" Member="Shots">
    <Type Name="Shot">
      <Column Name="ShotId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Shot_AnimalShot" Member="AnimalShots" ThisKey="ShotId" OtherKey="ShotId" Type="AnimalShot" />
    </Type>
  </Table>
  <Table Name="dbo.Species" Member="Species">
    <Type Name="Specy">
      <Column Name="SpeciesId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Specy_Animal" Member="Animals" ThisKey="SpeciesId" OtherKey="SpeciesId" Type="Animal" />
    </Type>
  </Table>
  <Table Name="dbo.USStates" Member="USStates">
    <Type Name="USState">
      <Column Name="USStateId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Abbreviation" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Association Name="USState_Address" Member="Addresses" ThisKey="USStateId" OtherKey="USStateId" Type="Address" />
    </Type>
  </Table>
</Database>